apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 2 # Specify the desired number of replicas
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app # Corrected the indentation here
          image: supraja13/reactapp
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080


  ---


apiVersion: v1
kind: Service
metadata:
  name: react-app
spec:
  selector:
    app: react-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
 

